### ISSUE TITLE
can't find module '@oieduardorabelo/use-navigator-online'

### ISSUE THREAD

**Issue by dingshaohua-com** [oieduardorabelo/use-navigator-online#1]
`➜  duo-office-editor git:(fix-optimize-nav) ✗ npm install @oieduardorabelo/use-navigator-online
+ @oieduardorabelo/use-navigator-online@1.0.5
added 1 package from 1 contributor and audited 14386 packages in 8.366s
found 0 vulnerabilities
`
![image](https://user-images.githubusercontent.com/18003391/59754976-bed8e000-92b9-11e9-9ff4-bcdeea382aec.png)

**Comment by oieduardorabelo** [comment]
hey @dshvv , the error is related to TypeScript types, atm this pkg doesn't have it

the module is working as expected:
https://codesandbox.io/s/keen-villani-1xy56?fontsize=14

**Comment by dingshaohua-com** [comment]
> hey @dshvv , the error is related to TypeScript types, atm this pkg doesn't have it
> 
> the module is working as expected:
> https://codesandbox.io/s/keen-villani-1xy56?fontsize=14

You are right, so am I. But I think the author should take care of the users of typescript. After all, more and more people are using it.

**Comment by oieduardorabelo** [comment]
nah, I'm good. feel free to submit a pr, otherwise, nah
