### ISSUE TITLE
avoid gatsby error by not initializing useState() with window object

### ISSUE THREAD

**Issue by bebbi** [oieduardorabelo/use-navigator-online#3]
Can we get rid of the window reference in the `useState` below?

```
useState(window.navigator.onLine)
```

As we're initializing it in a `useEffect` that might be enough?
With this, the hook is not compatible with `gatsby` which builds a SSR version of all pages and errors out because `window` is not defined.

**Comment by oieduardorabelo** [comment]
with https://github.com/oieduardorabelo/use-navigator-online/releases/tag/v5.0.0 it should work with SSR, have a look on the readme, there's a new `startOnline` option where you can control the initial render state, it defaults to `true`, so it can work with SSR
